  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module qy::credit_receipt { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappHub};
    use dubhe::dapp_system;
    use qy::dapp_key;
    use qy::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"credit_receipt";
    const OFFCHAIN: bool = false;

    public struct CreditReceipt has copy, drop, store {
        owner: address,
        amount: u64,
        admin: address,
        timestamp_ms: u64,
    }

    public fun new(owner: address, amount: u64, admin: address, timestamp_ms: u64): CreditReceipt {
        CreditReceipt {
            owner,
            amount,
            admin,
            timestamp_ms,
        }
    }

    public fun owner(self: &CreditReceipt): address {
        self.owner
    }

    public fun amount(self: &CreditReceipt): u64 {
        self.amount
    }

    public fun admin(self: &CreditReceipt): address {
        self.admin
    }

    public fun timestamp_ms(self: &CreditReceipt): u64 {
        self.timestamp_ms
    }

    public fun update_owner(self: &mut CreditReceipt, owner: address) {
        self.owner = owner
    }

    public fun update_amount(self: &mut CreditReceipt, amount: u64) {
        self.amount = amount
    }

    public fun update_admin(self: &mut CreditReceipt, admin: address) {
        self.admin = admin
    }

    public fun update_timestamp_ms(self: &mut CreditReceipt, timestamp_ms: u64) {
        self.timestamp_ms = timestamp_ms
    }

    public fun has(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        dapp_system::has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        dapp_system::ensure_has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has_not(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        dapp_system::ensure_has_not_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }
  

    public(package) fun delete(dapp_hub: &mut DappHub, resource_account: String, receipt_id: vector<u8>) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        dapp_system::delete_record<DappKey>(dapp_hub, dapp_key::new(), key_tuple, resource_account);
    }

    public fun get_owner(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 0);
        let mut bsc_type = sui::bcs::new(value);
        let owner = sui::bcs::peel_address(&mut bsc_type);
        owner
    }

    public(package) fun set_owner(dapp_hub: &mut DappHub, resource_account: String, receipt_id: vector<u8>, owner: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value = to_bytes(&owner);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 0, value, ctx);
    }

    public fun get_amount(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 1);
        let mut bsc_type = sui::bcs::new(value);
        let amount = sui::bcs::peel_u64(&mut bsc_type);
        amount
    }

    public(package) fun set_amount(dapp_hub: &mut DappHub, resource_account: String, receipt_id: vector<u8>, amount: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value = to_bytes(&amount);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 1, value, ctx);
    }

    public fun get_admin(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 2);
        let mut bsc_type = sui::bcs::new(value);
        let admin = sui::bcs::peel_address(&mut bsc_type);
        admin
    }

    public(package) fun set_admin(dapp_hub: &mut DappHub, resource_account: String, receipt_id: vector<u8>, admin: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value = to_bytes(&admin);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 2, value, ctx);
    }

    public fun get_timestamp_ms(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 3);
        let mut bsc_type = sui::bcs::new(value);
        let timestamp_ms = sui::bcs::peel_u64(&mut bsc_type);
        timestamp_ms
    }

    public(package) fun set_timestamp_ms(dapp_hub: &mut DappHub, resource_account: String, receipt_id: vector<u8>, timestamp_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value = to_bytes(&timestamp_ms);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 3, value, ctx);
    }

    public fun get(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>): (address, u64, address, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        let mut bsc_type = sui::bcs::new(value_tuple);
        let owner = sui::bcs::peel_address(&mut bsc_type);
        let amount = sui::bcs::peel_u64(&mut bsc_type);
        let admin = sui::bcs::peel_address(&mut bsc_type);
        let timestamp_ms = sui::bcs::peel_u64(&mut bsc_type);
        (owner, amount, admin, timestamp_ms)
    }

    public(package) fun set(dapp_hub: &mut DappHub, resource_account: String, receipt_id: vector<u8>, owner: address, amount: u64, admin: address, timestamp_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value_tuple = encode(owner, amount, admin, timestamp_ms);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun get_struct(dapp_hub: &DappHub, resource_account: String, receipt_id: vector<u8>): CreditReceipt {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        decode(value_tuple)
    }

    public(package) fun set_struct(dapp_hub: &mut DappHub, resource_account: String, receipt_id: vector<u8>, credit_receipt: CreditReceipt, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&receipt_id));
        let value_tuple = encode_struct(credit_receipt);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun encode(owner: address, amount: u64, admin: address, timestamp_ms: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&owner));
        value_tuple.push_back(to_bytes(&amount));
        value_tuple.push_back(to_bytes(&admin));
        value_tuple.push_back(to_bytes(&timestamp_ms));
        value_tuple
    }

    public fun encode_struct(credit_receipt: CreditReceipt): vector<vector<u8>> {
        encode(credit_receipt.owner, credit_receipt.amount, credit_receipt.admin, credit_receipt.timestamp_ms)
    }

    public fun decode(data: vector<u8>): CreditReceipt {
        let mut bsc_type = sui::bcs::new(data);
        let owner = sui::bcs::peel_address(&mut bsc_type);
        let amount = sui::bcs::peel_u64(&mut bsc_type);
        let admin = sui::bcs::peel_address(&mut bsc_type);
        let timestamp_ms = sui::bcs::peel_u64(&mut bsc_type);
        CreditReceipt {
            owner,
            amount,
            admin,
            timestamp_ms,
        }
    }
}