// Autogenerated-style resource module (handwritten)
// Schema / 结构:
// key: receipt_id (vector<u8>)
// value: owner, amount, admin, timestamp_ms
module qy::credit_receipt {
  use sui::bcs::{to_bytes};
  use sui::bcs;
  use std::ascii::{string, String};
  use dubhe::dapp_system;
  use dubhe::dapp_service::DappHub;
  use qy::dapp_key;
  use qy::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"credit_receipt";
  const TABLE_TYPE: vector<u8> = b"Resource";
  const OFFCHAIN: bool = false;

  public struct CreditReceipt has copy, drop, store {
    owner: address,
    amount: u64,
    admin: address,
    timestamp_ms: u64,
  }

  public fun new(owner: address, amount: u64, admin: address, timestamp_ms: u64): CreditReceipt {
    CreditReceipt { owner, amount, admin, timestamp_ms }
  }

  public fun owner(self: &CreditReceipt): address { self.owner }
  public fun amount(self: &CreditReceipt): u64 { self.amount }
  public fun admin(self: &CreditReceipt): address { self.admin }
  public fun timestamp_ms(self: &CreditReceipt): u64 { self.timestamp_ms }

  public fun get_table_id(): String { string(TABLE_NAME) }

  public fun get_key_schemas(): vector<String> {
    vector[string(b"vector<u8>")]
  }

  public fun get_value_schemas(): vector<String> {
    vector[
      string(b"address"),
      string(b"u64"),
      string(b"address"),
      string(b"u64")
    ]
  }

  public fun get_key_names(): vector<String> {
    vector[string(b"receipt_id")]
  }

  public fun get_value_names(): vector<String> {
    vector[
      string(b"owner"),
      string(b"amount"),
      string(b"admin"),
      string(b"timestamp_ms")
    ]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    dapp_system::register_table(
      dapp_hub,
      dapp_key::new(),
      string(TABLE_TYPE),
      get_table_id(),
      get_key_schemas(),
      get_key_names(),
      get_value_schemas(),
      get_value_names(),
      OFFCHAIN,
      ctx
    );
  }

  public fun has(dapp_hub: &DappHub, receipt_id: &vector<u8>): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(receipt_id));
    dapp_system::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, receipt_id: &vector<u8>) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(receipt_id));
    dapp_system::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, receipt_id: &vector<u8>) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(receipt_id));
    dapp_system::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun get_struct(dapp_hub: &DappHub, receipt_id: &vector<u8>): CreditReceipt {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(receipt_id));
    let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, receipt_id: vector<u8>, receipt: CreditReceipt) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&receipt_id));
    let value_tuple = encode_struct(receipt);
    dapp_system::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode_struct(receipt: CreditReceipt): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&receipt.owner));
    value_tuple.push_back(to_bytes(&receipt.amount));
    value_tuple.push_back(to_bytes(&receipt.admin));
    value_tuple.push_back(to_bytes(&receipt.timestamp_ms));
    value_tuple
  }

  public fun decode(data: vector<u8>): CreditReceipt {
    let mut b = bcs::new(data);
    let owner = bcs::peel_address(&mut b);
    let amount = bcs::peel_u64(&mut b);
    let admin = bcs::peel_address(&mut b);
    let timestamp_ms = bcs::peel_u64(&mut b);
    CreditReceipt { owner, amount, admin, timestamp_ms }
  }
}
