// Autogenerated-style resource module (handwritten)
// Schema / 结构:
// key: owner (address)
// value: available (u64)
module qy::ledger_balance {
  use sui::bcs::{to_bytes};
  use sui::bcs;
  use std::ascii::{string, String};
  use std::vector;
  use dubhe::dapp_system;
  use dubhe::dapp_service::DappHub;
  use qy::dapp_key;
  use qy::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"ledger_balance";
  const TABLE_TYPE: vector<u8> = b"Resource";
  const OFFCHAIN: bool = false;

  public struct Balance has copy, drop, store {
    available: u64,
  }

  public fun new(available: u64): Balance { Balance { available } }
  public fun available(self: &Balance): u64 { self.available }
  public fun update_available(self: &mut Balance, available: u64) { self.available = available }

  public fun get_table_id(): String { string(TABLE_NAME) }

  public fun get_key_schemas(): vector<String> {
    vector[string(b"address")]
  }

  public fun get_value_schemas(): vector<String> {
    vector[string(b"u64")]
  }

  public fun get_key_names(): vector<String> {
    vector[string(b"owner")]
  }

  public fun get_value_names(): vector<String> {
    vector[string(b"available")]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    dapp_system::register_table(
      dapp_hub,
      dapp_key::new(),
      string(TABLE_TYPE),
      get_table_id(),
      get_key_schemas(),
      get_key_names(),
      get_value_schemas(),
      get_value_names(),
      OFFCHAIN,
      ctx
    );
  }

  public fun has(dapp_hub: &DappHub, owner: address): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&owner));
    dapp_system::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, owner: address) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&owner));
    dapp_system::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun get_struct(dapp_hub: &DappHub, owner: address): Balance {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&owner));
    let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, owner: address, balance: Balance) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&owner));
    let value_tuple = encode_struct(balance);
    dapp_system::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode_struct(balance: Balance): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&balance.available));
    value_tuple
  }

  public fun decode(data: vector<u8>): Balance {
    let mut b = bcs::new(data);
    let available = bcs::peel_u64(&mut b);
    Balance { available }
  }
}
