// Autogenerated-style resource module (handwritten)
// Schema / 结构:
// key: order_id (u64)
// value: user, companion, rule_set_id, service_fee, deposit, platform_fee_bps,
//        status, created_at, finish_at, dispute_deadline, vault_service, vault_deposit,
//        evidence_hash, dispute_status, resolved_by, resolved_at
module qy::order {
  use sui::bcs::{to_bytes};
  use sui::bcs;
  use std::ascii::{string, String};
  use dubhe::dapp_system;
  use dubhe::dapp_service::DappHub;
  use qy::dapp_key;
  use qy::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"order";
  const TABLE_TYPE: vector<u8> = b"Resource";
  const OFFCHAIN: bool = false;

  public struct Order has copy, drop, store {
    user: address,
    companion: address,
    rule_set_id: u64,
    service_fee: u64,
    deposit: u64,
    platform_fee_bps: u64,
    status: u8,
    created_at: u64,
    finish_at: u64,
    dispute_deadline: u64,
    vault_service: u64,
    vault_deposit: u64,
    evidence_hash: vector<u8>,
    dispute_status: u8,
    resolved_by: address,
    resolved_at: u64,
  }

  public fun new(
    user: address,
    companion: address,
    rule_set_id: u64,
    service_fee: u64,
    deposit: u64,
    platform_fee_bps: u64,
    status: u8,
    created_at: u64,
    finish_at: u64,
    dispute_deadline: u64,
    vault_service: u64,
    vault_deposit: u64,
    evidence_hash: vector<u8>,
    dispute_status: u8,
    resolved_by: address,
    resolved_at: u64,
  ): Order {
    Order {
      user,
      companion,
      rule_set_id,
      service_fee,
      deposit,
      platform_fee_bps,
      status,
      created_at,
      finish_at,
      dispute_deadline,
      vault_service,
      vault_deposit,
      evidence_hash,
      dispute_status,
      resolved_by,
      resolved_at,
    }
  }

  public fun user(self: &Order): address { self.user }
  public fun companion(self: &Order): address { self.companion }
  public fun rule_set_id(self: &Order): u64 { self.rule_set_id }
  public fun service_fee(self: &Order): u64 { self.service_fee }
  public fun deposit(self: &Order): u64 { self.deposit }
  public fun platform_fee_bps(self: &Order): u64 { self.platform_fee_bps }
  public fun status(self: &Order): u8 { self.status }
  public fun created_at(self: &Order): u64 { self.created_at }
  public fun finish_at(self: &Order): u64 { self.finish_at }
  public fun dispute_deadline(self: &Order): u64 { self.dispute_deadline }
  public fun vault_service(self: &Order): u64 { self.vault_service }
  public fun vault_deposit(self: &Order): u64 { self.vault_deposit }
  public fun evidence_hash(self: &Order): vector<u8> { self.evidence_hash }
  public fun dispute_status(self: &Order): u8 { self.dispute_status }
  public fun resolved_by(self: &Order): address { self.resolved_by }
  public fun resolved_at(self: &Order): u64 { self.resolved_at }

  public fun update_status(self: &mut Order, status: u8) { self.status = status }
  public fun update_finish_at(self: &mut Order, finish_at: u64) { self.finish_at = finish_at }
  public fun update_dispute_deadline(self: &mut Order, dispute_deadline: u64) { self.dispute_deadline = dispute_deadline }
  public fun update_vault_service(self: &mut Order, vault_service: u64) { self.vault_service = vault_service }
  public fun update_vault_deposit(self: &mut Order, vault_deposit: u64) { self.vault_deposit = vault_deposit }
  public fun update_evidence_hash(self: &mut Order, evidence_hash: vector<u8>) { self.evidence_hash = evidence_hash }
  public fun update_dispute_status(self: &mut Order, dispute_status: u8) { self.dispute_status = dispute_status }
  public fun update_resolved_by(self: &mut Order, resolved_by: address) { self.resolved_by = resolved_by }
  public fun update_resolved_at(self: &mut Order, resolved_at: u64) { self.resolved_at = resolved_at }

  public fun get_table_id(): String { string(TABLE_NAME) }

  public fun get_key_schemas(): vector<String> {
    vector[string(b"u64")]
  }

  public fun get_value_schemas(): vector<String> {
    vector[
      string(b"address"),
      string(b"address"),
      string(b"u64"),
      string(b"u64"),
      string(b"u64"),
      string(b"u64"),
      string(b"u8"),
      string(b"u64"),
      string(b"u64"),
      string(b"u64"),
      string(b"u64"),
      string(b"u64"),
      string(b"vector<u8>"),
      string(b"u8"),
      string(b"address"),
      string(b"u64")
    ]
  }

  public fun get_key_names(): vector<String> {
    vector[string(b"order_id")]
  }

  public fun get_value_names(): vector<String> {
    vector[
      string(b"user"),
      string(b"companion"),
      string(b"rule_set_id"),
      string(b"service_fee"),
      string(b"deposit"),
      string(b"platform_fee_bps"),
      string(b"status"),
      string(b"created_at"),
      string(b"finish_at"),
      string(b"dispute_deadline"),
      string(b"vault_service"),
      string(b"vault_deposit"),
      string(b"evidence_hash"),
      string(b"dispute_status"),
      string(b"resolved_by"),
      string(b"resolved_at")
    ]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    dapp_system::register_table(
      dapp_hub,
      dapp_key::new(),
      string(TABLE_TYPE),
      get_table_id(),
      get_key_schemas(),
      get_key_names(),
      get_value_schemas(),
      get_value_names(),
      OFFCHAIN,
      ctx
    );
  }

  public fun has(dapp_hub: &DappHub, order_id: u64): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&order_id));
    dapp_system::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, order_id: u64) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&order_id));
    dapp_system::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, order_id: u64) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&order_id));
    dapp_system::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun get_struct(dapp_hub: &DappHub, order_id: u64): Order {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&order_id));
    let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, order_id: u64, order: Order) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&order_id));
    let value_tuple = encode_struct(order);
    dapp_system::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode_struct(order: Order): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&order.user));
    value_tuple.push_back(to_bytes(&order.companion));
    value_tuple.push_back(to_bytes(&order.rule_set_id));
    value_tuple.push_back(to_bytes(&order.service_fee));
    value_tuple.push_back(to_bytes(&order.deposit));
    value_tuple.push_back(to_bytes(&order.platform_fee_bps));
    value_tuple.push_back(to_bytes(&order.status));
    value_tuple.push_back(to_bytes(&order.created_at));
    value_tuple.push_back(to_bytes(&order.finish_at));
    value_tuple.push_back(to_bytes(&order.dispute_deadline));
    value_tuple.push_back(to_bytes(&order.vault_service));
    value_tuple.push_back(to_bytes(&order.vault_deposit));
    value_tuple.push_back(to_bytes(&order.evidence_hash));
    value_tuple.push_back(to_bytes(&order.dispute_status));
    value_tuple.push_back(to_bytes(&order.resolved_by));
    value_tuple.push_back(to_bytes(&order.resolved_at));
    value_tuple
  }

  public fun decode(data: vector<u8>): Order {
    let mut b = bcs::new(data);
    let user = bcs::peel_address(&mut b);
    let companion = bcs::peel_address(&mut b);
    let rule_set_id = bcs::peel_u64(&mut b);
    let service_fee = bcs::peel_u64(&mut b);
    let deposit = bcs::peel_u64(&mut b);
    let platform_fee_bps = bcs::peel_u64(&mut b);
    let status = bcs::peel_u8(&mut b);
    let created_at = bcs::peel_u64(&mut b);
    let finish_at = bcs::peel_u64(&mut b);
    let dispute_deadline = bcs::peel_u64(&mut b);
    let vault_service = bcs::peel_u64(&mut b);
    let vault_deposit = bcs::peel_u64(&mut b);
    let evidence_hash = bcs::peel_vec_u8(&mut b);
    let dispute_status = bcs::peel_u8(&mut b);
    let resolved_by = bcs::peel_address(&mut b);
    let resolved_at = bcs::peel_u64(&mut b);
    Order {
      user,
      companion,
      rule_set_id,
      service_fee,
      deposit,
      platform_fee_bps,
      status,
      created_at,
      finish_at,
      dispute_deadline,
      vault_service,
      vault_deposit,
      evidence_hash,
      dispute_status,
      resolved_by,
      resolved_at,
    }
  }
}
