  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module qy::order { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappHub};
    use dubhe::dapp_system;
    use qy::dapp_key;
    use qy::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"order";
    const OFFCHAIN: bool = false;

    public struct Order has copy, drop, store {
        user: address,
        companion: address,
        rule_set_id: u64,
        service_fee: u64,
        deposit: u64,
        platform_fee_bps: u64,
        status: u8,
        created_at: u64,
        finish_at: u64,
        dispute_deadline: u64,
        vault_service: u64,
        vault_deposit: u64,
        evidence_hash: vector<u8>,
        dispute_status: u8,
        resolved_by: address,
        resolved_at: u64,
    }

    public fun new(user: address, companion: address, rule_set_id: u64, service_fee: u64, deposit: u64, platform_fee_bps: u64, status: u8, created_at: u64, finish_at: u64, dispute_deadline: u64, vault_service: u64, vault_deposit: u64, evidence_hash: vector<u8>, dispute_status: u8, resolved_by: address, resolved_at: u64): Order {
        Order {
            user,
            companion,
            rule_set_id,
            service_fee,
            deposit,
            platform_fee_bps,
            status,
            created_at,
            finish_at,
            dispute_deadline,
            vault_service,
            vault_deposit,
            evidence_hash,
            dispute_status,
            resolved_by,
            resolved_at,
        }
    }

    public fun user(self: &Order): address {
        self.user
    }

    public fun companion(self: &Order): address {
        self.companion
    }

    public fun rule_set_id(self: &Order): u64 {
        self.rule_set_id
    }

    public fun service_fee(self: &Order): u64 {
        self.service_fee
    }

    public fun deposit(self: &Order): u64 {
        self.deposit
    }

    public fun platform_fee_bps(self: &Order): u64 {
        self.platform_fee_bps
    }

    public fun status(self: &Order): u8 {
        self.status
    }

    public fun created_at(self: &Order): u64 {
        self.created_at
    }

    public fun finish_at(self: &Order): u64 {
        self.finish_at
    }

    public fun dispute_deadline(self: &Order): u64 {
        self.dispute_deadline
    }

    public fun vault_service(self: &Order): u64 {
        self.vault_service
    }

    public fun vault_deposit(self: &Order): u64 {
        self.vault_deposit
    }

    public fun evidence_hash(self: &Order): vector<u8> {
        self.evidence_hash
    }

    public fun dispute_status(self: &Order): u8 {
        self.dispute_status
    }

    public fun resolved_by(self: &Order): address {
        self.resolved_by
    }

    public fun resolved_at(self: &Order): u64 {
        self.resolved_at
    }

    public fun update_user(self: &mut Order, user: address) {
        self.user = user
    }

    public fun update_companion(self: &mut Order, companion: address) {
        self.companion = companion
    }

    public fun update_rule_set_id(self: &mut Order, rule_set_id: u64) {
        self.rule_set_id = rule_set_id
    }

    public fun update_service_fee(self: &mut Order, service_fee: u64) {
        self.service_fee = service_fee
    }

    public fun update_deposit(self: &mut Order, deposit: u64) {
        self.deposit = deposit
    }

    public fun update_platform_fee_bps(self: &mut Order, platform_fee_bps: u64) {
        self.platform_fee_bps = platform_fee_bps
    }

    public fun update_status(self: &mut Order, status: u8) {
        self.status = status
    }

    public fun update_created_at(self: &mut Order, created_at: u64) {
        self.created_at = created_at
    }

    public fun update_finish_at(self: &mut Order, finish_at: u64) {
        self.finish_at = finish_at
    }

    public fun update_dispute_deadline(self: &mut Order, dispute_deadline: u64) {
        self.dispute_deadline = dispute_deadline
    }

    public fun update_vault_service(self: &mut Order, vault_service: u64) {
        self.vault_service = vault_service
    }

    public fun update_vault_deposit(self: &mut Order, vault_deposit: u64) {
        self.vault_deposit = vault_deposit
    }

    public fun update_evidence_hash(self: &mut Order, evidence_hash: vector<u8>) {
        self.evidence_hash = evidence_hash
    }

    public fun update_dispute_status(self: &mut Order, dispute_status: u8) {
        self.dispute_status = dispute_status
    }

    public fun update_resolved_by(self: &mut Order, resolved_by: address) {
        self.resolved_by = resolved_by
    }

    public fun update_resolved_at(self: &mut Order, resolved_at: u64) {
        self.resolved_at = resolved_at
    }

    public fun has(dapp_hub: &DappHub, resource_account: String, order_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        dapp_system::has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has(dapp_hub: &DappHub, resource_account: String, order_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        dapp_system::ensure_has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has_not(dapp_hub: &DappHub, resource_account: String, order_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        dapp_system::ensure_has_not_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }
  

    public(package) fun delete(dapp_hub: &mut DappHub, resource_account: String, order_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        dapp_system::delete_record<DappKey>(dapp_hub, dapp_key::new(), key_tuple, resource_account);
    }

    public fun get_user(dapp_hub: &DappHub, resource_account: String, order_id: u64): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 0);
        let mut bsc_type = sui::bcs::new(value);
        let user = sui::bcs::peel_address(&mut bsc_type);
        user
    }

    public(package) fun set_user(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, user: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&user);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 0, value, ctx);
    }

    public fun get_companion(dapp_hub: &DappHub, resource_account: String, order_id: u64): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 1);
        let mut bsc_type = sui::bcs::new(value);
        let companion = sui::bcs::peel_address(&mut bsc_type);
        companion
    }

    public(package) fun set_companion(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, companion: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&companion);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 1, value, ctx);
    }

    public fun get_rule_set_id(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 2);
        let mut bsc_type = sui::bcs::new(value);
        let rule_set_id = sui::bcs::peel_u64(&mut bsc_type);
        rule_set_id
    }

    public(package) fun set_rule_set_id(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, rule_set_id: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&rule_set_id);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 2, value, ctx);
    }

    public fun get_service_fee(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 3);
        let mut bsc_type = sui::bcs::new(value);
        let service_fee = sui::bcs::peel_u64(&mut bsc_type);
        service_fee
    }

    public(package) fun set_service_fee(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, service_fee: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&service_fee);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 3, value, ctx);
    }

    public fun get_deposit(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 4);
        let mut bsc_type = sui::bcs::new(value);
        let deposit = sui::bcs::peel_u64(&mut bsc_type);
        deposit
    }

    public(package) fun set_deposit(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, deposit: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&deposit);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 4, value, ctx);
    }

    public fun get_platform_fee_bps(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 5);
        let mut bsc_type = sui::bcs::new(value);
        let platform_fee_bps = sui::bcs::peel_u64(&mut bsc_type);
        platform_fee_bps
    }

    public(package) fun set_platform_fee_bps(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, platform_fee_bps: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&platform_fee_bps);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 5, value, ctx);
    }

    public fun get_status(dapp_hub: &DappHub, resource_account: String, order_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 6);
        let mut bsc_type = sui::bcs::new(value);
        let status = sui::bcs::peel_u8(&mut bsc_type);
        status
    }

    public(package) fun set_status(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, status: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&status);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 6, value, ctx);
    }

    public fun get_created_at(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 7);
        let mut bsc_type = sui::bcs::new(value);
        let created_at = sui::bcs::peel_u64(&mut bsc_type);
        created_at
    }

    public(package) fun set_created_at(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, created_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&created_at);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 7, value, ctx);
    }

    public fun get_finish_at(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 8);
        let mut bsc_type = sui::bcs::new(value);
        let finish_at = sui::bcs::peel_u64(&mut bsc_type);
        finish_at
    }

    public(package) fun set_finish_at(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, finish_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&finish_at);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 8, value, ctx);
    }

    public fun get_dispute_deadline(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 9);
        let mut bsc_type = sui::bcs::new(value);
        let dispute_deadline = sui::bcs::peel_u64(&mut bsc_type);
        dispute_deadline
    }

    public(package) fun set_dispute_deadline(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, dispute_deadline: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&dispute_deadline);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 9, value, ctx);
    }

    public fun get_vault_service(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 10);
        let mut bsc_type = sui::bcs::new(value);
        let vault_service = sui::bcs::peel_u64(&mut bsc_type);
        vault_service
    }

    public(package) fun set_vault_service(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, vault_service: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&vault_service);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 10, value, ctx);
    }

    public fun get_vault_deposit(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 11);
        let mut bsc_type = sui::bcs::new(value);
        let vault_deposit = sui::bcs::peel_u64(&mut bsc_type);
        vault_deposit
    }

    public(package) fun set_vault_deposit(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, vault_deposit: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&vault_deposit);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 11, value, ctx);
    }

    public fun get_evidence_hash(dapp_hub: &DappHub, resource_account: String, order_id: u64): vector<u8> {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 12);
        let mut bsc_type = sui::bcs::new(value);
        let evidence_hash = sui::bcs::peel_vec_u8(&mut bsc_type);
        evidence_hash
    }

    public(package) fun set_evidence_hash(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, evidence_hash: vector<u8>, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&evidence_hash);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 12, value, ctx);
    }

    public fun get_dispute_status(dapp_hub: &DappHub, resource_account: String, order_id: u64): u8 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 13);
        let mut bsc_type = sui::bcs::new(value);
        let dispute_status = sui::bcs::peel_u8(&mut bsc_type);
        dispute_status
    }

    public(package) fun set_dispute_status(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, dispute_status: u8, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&dispute_status);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 13, value, ctx);
    }

    public fun get_resolved_by(dapp_hub: &DappHub, resource_account: String, order_id: u64): address {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 14);
        let mut bsc_type = sui::bcs::new(value);
        let resolved_by = sui::bcs::peel_address(&mut bsc_type);
        resolved_by
    }

    public(package) fun set_resolved_by(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, resolved_by: address, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&resolved_by);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 14, value, ctx);
    }

    public fun get_resolved_at(dapp_hub: &DappHub, resource_account: String, order_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 15);
        let mut bsc_type = sui::bcs::new(value);
        let resolved_at = sui::bcs::peel_u64(&mut bsc_type);
        resolved_at
    }

    public(package) fun set_resolved_at(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, resolved_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value = to_bytes(&resolved_at);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 15, value, ctx);
    }

    public fun get(dapp_hub: &DappHub, resource_account: String, order_id: u64): (address, address, u64, u64, u64, u64, u8, u64, u64, u64, u64, u64, vector<u8>, u8, address, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        let mut bsc_type = sui::bcs::new(value_tuple);
        let user = sui::bcs::peel_address(&mut bsc_type);
        let companion = sui::bcs::peel_address(&mut bsc_type);
        let rule_set_id = sui::bcs::peel_u64(&mut bsc_type);
        let service_fee = sui::bcs::peel_u64(&mut bsc_type);
        let deposit = sui::bcs::peel_u64(&mut bsc_type);
        let platform_fee_bps = sui::bcs::peel_u64(&mut bsc_type);
        let status = sui::bcs::peel_u8(&mut bsc_type);
        let created_at = sui::bcs::peel_u64(&mut bsc_type);
        let finish_at = sui::bcs::peel_u64(&mut bsc_type);
        let dispute_deadline = sui::bcs::peel_u64(&mut bsc_type);
        let vault_service = sui::bcs::peel_u64(&mut bsc_type);
        let vault_deposit = sui::bcs::peel_u64(&mut bsc_type);
        let evidence_hash = sui::bcs::peel_vec_u8(&mut bsc_type);
        let dispute_status = sui::bcs::peel_u8(&mut bsc_type);
        let resolved_by = sui::bcs::peel_address(&mut bsc_type);
        let resolved_at = sui::bcs::peel_u64(&mut bsc_type);
        (user, companion, rule_set_id, service_fee, deposit, platform_fee_bps, status, created_at, finish_at, dispute_deadline, vault_service, vault_deposit, evidence_hash, dispute_status, resolved_by, resolved_at)
    }

    public(package) fun set(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, user: address, companion: address, rule_set_id: u64, service_fee: u64, deposit: u64, platform_fee_bps: u64, status: u8, created_at: u64, finish_at: u64, dispute_deadline: u64, vault_service: u64, vault_deposit: u64, evidence_hash: vector<u8>, dispute_status: u8, resolved_by: address, resolved_at: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value_tuple = encode(user, companion, rule_set_id, service_fee, deposit, platform_fee_bps, status, created_at, finish_at, dispute_deadline, vault_service, vault_deposit, evidence_hash, dispute_status, resolved_by, resolved_at);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun get_struct(dapp_hub: &DappHub, resource_account: String, order_id: u64): Order {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        decode(value_tuple)
    }

    public(package) fun set_struct(dapp_hub: &mut DappHub, resource_account: String, order_id: u64, order: Order, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&order_id));
        let value_tuple = encode_struct(order);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun encode(user: address, companion: address, rule_set_id: u64, service_fee: u64, deposit: u64, platform_fee_bps: u64, status: u8, created_at: u64, finish_at: u64, dispute_deadline: u64, vault_service: u64, vault_deposit: u64, evidence_hash: vector<u8>, dispute_status: u8, resolved_by: address, resolved_at: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&user));
        value_tuple.push_back(to_bytes(&companion));
        value_tuple.push_back(to_bytes(&rule_set_id));
        value_tuple.push_back(to_bytes(&service_fee));
        value_tuple.push_back(to_bytes(&deposit));
        value_tuple.push_back(to_bytes(&platform_fee_bps));
        value_tuple.push_back(to_bytes(&status));
        value_tuple.push_back(to_bytes(&created_at));
        value_tuple.push_back(to_bytes(&finish_at));
        value_tuple.push_back(to_bytes(&dispute_deadline));
        value_tuple.push_back(to_bytes(&vault_service));
        value_tuple.push_back(to_bytes(&vault_deposit));
        value_tuple.push_back(to_bytes(&evidence_hash));
        value_tuple.push_back(to_bytes(&dispute_status));
        value_tuple.push_back(to_bytes(&resolved_by));
        value_tuple.push_back(to_bytes(&resolved_at));
        value_tuple
    }

    public fun encode_struct(order: Order): vector<vector<u8>> {
        encode(order.user, order.companion, order.rule_set_id, order.service_fee, order.deposit, order.platform_fee_bps, order.status, order.created_at, order.finish_at, order.dispute_deadline, order.vault_service, order.vault_deposit, order.evidence_hash, order.dispute_status, order.resolved_by, order.resolved_at)
    }

    public fun decode(data: vector<u8>): Order {
        let mut bsc_type = sui::bcs::new(data);
        let user = sui::bcs::peel_address(&mut bsc_type);
        let companion = sui::bcs::peel_address(&mut bsc_type);
        let rule_set_id = sui::bcs::peel_u64(&mut bsc_type);
        let service_fee = sui::bcs::peel_u64(&mut bsc_type);
        let deposit = sui::bcs::peel_u64(&mut bsc_type);
        let platform_fee_bps = sui::bcs::peel_u64(&mut bsc_type);
        let status = sui::bcs::peel_u8(&mut bsc_type);
        let created_at = sui::bcs::peel_u64(&mut bsc_type);
        let finish_at = sui::bcs::peel_u64(&mut bsc_type);
        let dispute_deadline = sui::bcs::peel_u64(&mut bsc_type);
        let vault_service = sui::bcs::peel_u64(&mut bsc_type);
        let vault_deposit = sui::bcs::peel_u64(&mut bsc_type);
        let evidence_hash = sui::bcs::peel_vec_u8(&mut bsc_type);
        let dispute_status = sui::bcs::peel_u8(&mut bsc_type);
        let resolved_by = sui::bcs::peel_address(&mut bsc_type);
        let resolved_at = sui::bcs::peel_u64(&mut bsc_type);
        Order {
            user,
            companion,
            rule_set_id,
            service_fee,
            deposit,
            platform_fee_bps,
            status,
            created_at,
            finish_at,
            dispute_deadline,
            vault_service,
            vault_deposit,
            evidence_hash,
            dispute_status,
            resolved_by,
            resolved_at,
        }
    }
}