// Autogenerated-style resource module (handwritten)
// Schema / 结构:
// key: rule_set_id (u64)
// value: rule_hash, dispute_window_ms, platform_fee_bps
module qy::ruleset {
  use sui::bcs::{to_bytes};
  use sui::bcs;
  use std::ascii::{string, String};
  use std::vector;
  use dubhe::dapp_system;
  use dubhe::dapp_service::DappHub;
  use qy::dapp_key;
  use qy::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"ruleset";
  const TABLE_TYPE: vector<u8> = b"Resource";
  const OFFCHAIN: bool = false;

  public struct Ruleset has copy, drop, store {
    rule_hash: vector<u8>,
    dispute_window_ms: u64,
    platform_fee_bps: u64,
  }

  public fun new(rule_hash: vector<u8>, dispute_window_ms: u64, platform_fee_bps: u64): Ruleset {
    Ruleset { rule_hash, dispute_window_ms, platform_fee_bps }
  }

  public fun rule_hash(self: &Ruleset): vector<u8> { self.rule_hash }
  public fun dispute_window_ms(self: &Ruleset): u64 { self.dispute_window_ms }
  public fun platform_fee_bps(self: &Ruleset): u64 { self.platform_fee_bps }

  public fun update_rule_hash(self: &mut Ruleset, rule_hash: vector<u8>) { self.rule_hash = rule_hash }
  public fun update_dispute_window_ms(self: &mut Ruleset, dispute_window_ms: u64) { self.dispute_window_ms = dispute_window_ms }
  public fun update_platform_fee_bps(self: &mut Ruleset, platform_fee_bps: u64) { self.platform_fee_bps = platform_fee_bps }

  public fun get_table_id(): String { string(TABLE_NAME) }

  public fun get_key_schemas(): vector<String> {
    vector[string(b"u64")]
  }

  public fun get_value_schemas(): vector<String> {
    vector[
      string(b"vector<u8>"),
      string(b"u64"),
      string(b"u64")
    ]
  }

  public fun get_key_names(): vector<String> {
    vector[string(b"rule_set_id")]
  }

  public fun get_value_names(): vector<String> {
    vector[
      string(b"rule_hash"),
      string(b"dispute_window_ms"),
      string(b"platform_fee_bps")
    ]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    dapp_system::register_table(
      dapp_hub,
      dapp_key::new(),
      string(TABLE_TYPE),
      get_table_id(),
      get_key_schemas(),
      get_key_names(),
      get_value_schemas(),
      get_value_names(),
      OFFCHAIN,
      ctx
    );
  }

  public fun has(dapp_hub: &DappHub, rule_set_id: u64): bool {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&rule_set_id));
    dapp_system::has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_has(dapp_hub: &DappHub, rule_set_id: u64) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&rule_set_id));
    dapp_system::ensure_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun ensure_not_has(dapp_hub: &DappHub, rule_set_id: u64) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&rule_set_id));
    dapp_system::ensure_not_has_record<DappKey>(dapp_hub, get_table_id(), key_tuple)
  }

  public fun get_struct(dapp_hub: &DappHub, rule_set_id: u64): Ruleset {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&rule_set_id));
    let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, get_table_id(), key_tuple);
    decode(value_tuple)
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, rule_set_id: u64, ruleset: Ruleset) {
    let mut key_tuple = vector::empty();
    key_tuple.push_back(to_bytes(&rule_set_id));
    let value_tuple = encode_struct(ruleset);
    dapp_system::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode_struct(ruleset: Ruleset): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&ruleset.rule_hash));
    value_tuple.push_back(to_bytes(&ruleset.dispute_window_ms));
    value_tuple.push_back(to_bytes(&ruleset.platform_fee_bps));
    value_tuple
  }

  public fun decode(data: vector<u8>): Ruleset {
    let mut b = bcs::new(data);
    let rule_hash = bcs::peel_vec_u8(&mut b);
    let dispute_window_ms = bcs::peel_u64(&mut b);
    let platform_fee_bps = bcs::peel_u64(&mut b);
    Ruleset { rule_hash, dispute_window_ms, platform_fee_bps }
  }
}
