  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module qy::ruleset { 
    use sui::bcs::{to_bytes};
    use std::ascii::{string, String, into_bytes};
    use dubhe::table_id;
    use dubhe::dapp_service::{Self, DappHub};
    use dubhe::dapp_system;
    use qy::dapp_key;
    use qy::dapp_key::DappKey;


    const TABLE_NAME: vector<u8> = b"ruleset";
    const OFFCHAIN: bool = false;

    public struct Ruleset has copy, drop, store {
        rule_hash: vector<u8>,
        dispute_window_ms: u64,
        platform_fee_bps: u64,
    }

    public fun new(rule_hash: vector<u8>, dispute_window_ms: u64, platform_fee_bps: u64): Ruleset {
        Ruleset {
            rule_hash,
            dispute_window_ms,
            platform_fee_bps,
        }
    }

    public fun rule_hash(self: &Ruleset): vector<u8> {
        self.rule_hash
    }

    public fun dispute_window_ms(self: &Ruleset): u64 {
        self.dispute_window_ms
    }

    public fun platform_fee_bps(self: &Ruleset): u64 {
        self.platform_fee_bps
    }

    public fun update_rule_hash(self: &mut Ruleset, rule_hash: vector<u8>) {
        self.rule_hash = rule_hash
    }

    public fun update_dispute_window_ms(self: &mut Ruleset, dispute_window_ms: u64) {
        self.dispute_window_ms = dispute_window_ms
    }

    public fun update_platform_fee_bps(self: &mut Ruleset, platform_fee_bps: u64) {
        self.platform_fee_bps = platform_fee_bps
    }

    public fun has(dapp_hub: &DappHub, resource_account: String, rule_set_id: u64): bool {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        dapp_system::has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has(dapp_hub: &DappHub, resource_account: String, rule_set_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        dapp_system::ensure_has_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }

    public fun ensure_has_not(dapp_hub: &DappHub, resource_account: String, rule_set_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        dapp_system::ensure_has_not_record<DappKey>(dapp_hub, resource_account, key_tuple)
    }
  

    public(package) fun delete(dapp_hub: &mut DappHub, resource_account: String, rule_set_id: u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        dapp_system::delete_record<DappKey>(dapp_hub, dapp_key::new(), key_tuple, resource_account);
    }

    public fun get_rule_hash(dapp_hub: &DappHub, resource_account: String, rule_set_id: u64): vector<u8> {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 0);
        let mut bsc_type = sui::bcs::new(value);
        let rule_hash = sui::bcs::peel_vec_u8(&mut bsc_type);
        rule_hash
    }

    public(package) fun set_rule_hash(dapp_hub: &mut DappHub, resource_account: String, rule_set_id: u64, rule_hash: vector<u8>, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value = to_bytes(&rule_hash);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 0, value, ctx);
    }

    public fun get_dispute_window_ms(dapp_hub: &DappHub, resource_account: String, rule_set_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 1);
        let mut bsc_type = sui::bcs::new(value);
        let dispute_window_ms = sui::bcs::peel_u64(&mut bsc_type);
        dispute_window_ms
    }

    public(package) fun set_dispute_window_ms(dapp_hub: &mut DappHub, resource_account: String, rule_set_id: u64, dispute_window_ms: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value = to_bytes(&dispute_window_ms);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 1, value, ctx);
    }

    public fun get_platform_fee_bps(dapp_hub: &DappHub, resource_account: String, rule_set_id: u64): u64 {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value = dapp_system::get_field<DappKey>(dapp_hub, resource_account, key_tuple, 2);
        let mut bsc_type = sui::bcs::new(value);
        let platform_fee_bps = sui::bcs::peel_u64(&mut bsc_type);
        platform_fee_bps
    }

    public(package) fun set_platform_fee_bps(dapp_hub: &mut DappHub, resource_account: String, rule_set_id: u64, platform_fee_bps: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value = to_bytes(&platform_fee_bps);
        dapp_system::set_field(dapp_hub, dapp_key::new(), resource_account, key_tuple, 2, value, ctx);
    }

    public fun get(dapp_hub: &DappHub, resource_account: String, rule_set_id: u64): (vector<u8>, u64, u64) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        let mut bsc_type = sui::bcs::new(value_tuple);
        let rule_hash = sui::bcs::peel_vec_u8(&mut bsc_type);
        let dispute_window_ms = sui::bcs::peel_u64(&mut bsc_type);
        let platform_fee_bps = sui::bcs::peel_u64(&mut bsc_type);
        (rule_hash, dispute_window_ms, platform_fee_bps)
    }

    public(package) fun set(dapp_hub: &mut DappHub, resource_account: String, rule_set_id: u64, rule_hash: vector<u8>, dispute_window_ms: u64, platform_fee_bps: u64, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value_tuple = encode(rule_hash, dispute_window_ms, platform_fee_bps);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun get_struct(dapp_hub: &DappHub, resource_account: String, rule_set_id: u64): Ruleset {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value_tuple = dapp_system::get_record<DappKey>(dapp_hub, resource_account, key_tuple);
        decode(value_tuple)
    }

    public(package) fun set_struct(dapp_hub: &mut DappHub, resource_account: String, rule_set_id: u64, ruleset: Ruleset, ctx: &mut TxContext) {
        let mut key_tuple = vector::empty();
        key_tuple.push_back(TABLE_NAME);
        key_tuple.push_back(to_bytes(&rule_set_id));
        let value_tuple = encode_struct(ruleset);
        dapp_system::set_record(dapp_hub, dapp_key::new(), key_tuple, value_tuple, resource_account, OFFCHAIN, ctx);
    }

    public fun encode(rule_hash: vector<u8>, dispute_window_ms: u64, platform_fee_bps: u64): vector<vector<u8>> {
        let mut value_tuple = vector::empty();
        value_tuple.push_back(to_bytes(&rule_hash));
        value_tuple.push_back(to_bytes(&dispute_window_ms));
        value_tuple.push_back(to_bytes(&platform_fee_bps));
        value_tuple
    }

    public fun encode_struct(ruleset: Ruleset): vector<vector<u8>> {
        encode(ruleset.rule_hash, ruleset.dispute_window_ms, ruleset.platform_fee_bps)
    }

    public fun decode(data: vector<u8>): Ruleset {
        let mut bsc_type = sui::bcs::new(data);
        let rule_hash = sui::bcs::peel_vec_u8(&mut bsc_type);
        let dispute_window_ms = sui::bcs::peel_u64(&mut bsc_type);
        let platform_fee_bps = sui::bcs::peel_u64(&mut bsc_type);
        Ruleset {
            rule_hash,
            dispute_window_ms,
            platform_fee_bps,
        }
    }
}