import { defineCloudflareConfig } from "@opennextjs/cloudflare";
// import r2IncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/r2-incremental-cache";

const config = defineCloudflareConfig({
	// For best results consider enabling R2 caching
	// See https://opennext.js.org/cloudflare/caching for more details
	// incrementalCache: r2IncrementalCache
});

config.default.minify = true;
config.functions = {
	...(config.functions ?? {}),
	admin: {
		routes: [
			"app/admin/(auth)/login/page",
			"app/admin/(panel)/analytics/page",
			"app/admin/(panel)/announcements/page",
			"app/admin/(panel)/audit/page",
			"app/admin/(panel)/chain/page",
			"app/admin/(panel)/coupons/page",
			"app/admin/(panel)/dashboard/page",
			"app/admin/(panel)/disputes/page",
			"app/admin/(panel)/duo-orders/page",
			"app/admin/(panel)/earnings/page",
			"app/admin/(panel)/examiners/page",
			"app/admin/(panel)/guardians/page",
			"app/admin/(panel)/invoices/page",
			"app/admin/(panel)/ledger/page",
			"app/admin/(panel)/live-applications/page",
			"app/admin/(panel)/mantou/page",
			"app/admin/(panel)/orders/[orderId]/page",
			"app/admin/(panel)/orders/page",
			"app/admin/(panel)/page",
			"app/admin/(panel)/payments/page",
			"app/admin/(panel)/players/page",
			"app/admin/(panel)/reconcile/page",
			"app/admin/(panel)/redeem/page",
			"app/admin/(panel)/referral/page",
			"app/admin/(panel)/revenue/page",
			"app/admin/(panel)/support/page",
			"app/admin/(panel)/tokens/page",
			"app/admin/(panel)/vip/page",
			"app/api/admin/analytics/route",
			"app/api/admin/analytics/trend/route",
			"app/api/admin/announcements/[announcementId]/route",
			"app/api/admin/announcements/bulk-delete/route",
			"app/api/admin/announcements/route",
			"app/api/admin/audit/route",
			"app/api/admin/backup/route",
			"app/api/admin/chain/auto-cancel/route",
			"app/api/admin/chain/auto-finalize/route",
			"app/api/admin/chain/cache/route",
			"app/api/admin/chain/cancel/route",
			"app/api/admin/chain/cleanup-missing/route",
			"app/api/admin/chain/logs/route",
			"app/api/admin/chain/order/[orderId]/route",
			"app/api/admin/chain/orders/route",
			"app/api/admin/chain/reconcile/route",
			"app/api/admin/chain/resolve/route",
			"app/api/admin/coupons/[couponId]/route",
			"app/api/admin/coupons/route",
			"app/api/admin/customer-tags/route",
			"app/api/admin/dashboard/route",
			"app/api/admin/disputes/route",
			"app/api/admin/earnings/route",
			"app/api/admin/examiners/[applicationId]/route",
			"app/api/admin/examiners/route",
			"app/api/admin/feature-flags/route",
			"app/api/admin/guardians/[applicationId]/route",
			"app/api/admin/guardians/route",
			"app/api/admin/invoices/[invoiceId]/route",
			"app/api/admin/invoices/route",
			"app/api/admin/kook/route",
			"app/api/admin/ledger/credit/route",
			"app/api/admin/live-applications/[applicationId]/route",
			"app/api/admin/live-applications/route",
			"app/api/admin/login/route",
			"app/api/admin/logout/route",
			"app/api/admin/mantou/withdraws/[requestId]/route",
			"app/api/admin/mantou/withdraws/route",
			"app/api/admin/me/route",
			"app/api/admin/orders/[orderId]/route",
			"app/api/admin/orders/bulk-delete/route",
			"app/api/admin/orders/cleanup-e2e/route",
			"app/api/admin/orders/export/route",
			"app/api/admin/orders/route",
			"app/api/admin/payments/route",
			"app/api/admin/performance/route",
			"app/api/admin/players/[playerId]/route",
			"app/api/admin/players/bulk-delete/route",
			"app/api/admin/players/route",
			"app/api/admin/reconcile/route",
			"app/api/admin/redeem/codes/[codeId]/route",
			"app/api/admin/redeem/codes/route",
			"app/api/admin/redeem/records/route",
			"app/api/admin/referral/config/route",
			"app/api/admin/referral/list/route",
			"app/api/admin/refresh/route",
			"app/api/admin/revenue/route",
			"app/api/admin/stats/route",
			"app/api/admin/support/[ticketId]/route",
			"app/api/admin/support/route",
			"app/api/admin/tokens/[tokenId]/route",
			"app/api/admin/tokens/route",
			"app/api/admin/vip/members/[memberId]/route",
			"app/api/admin/vip/members/route",
			"app/api/admin/vip/requests/[requestId]/route",
			"app/api/admin/vip/requests/route",
			"app/api/admin/vip/tiers/[tierId]/route",
			"app/api/admin/vip/tiers/route",
		],
		patterns: ["/admin", "/admin/*", "/api/admin", "/api/admin/*"],
	},
};

export default config;
