import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test/setup.ts"],
    coverage: {
      provider: "v8",
      include: ["src/lib/**/*.ts"],
      exclude: [
        "src/lib/db.ts",
        "src/lib/admin/admin-store.ts",
        "src/lib/admin/admin-store-utils.ts",
        "src/lib/admin/admin-types.ts",
        "src/lib/admin/admin-auth.ts",
        "src/lib/admin/admin-audit.ts",
        "src/lib/admin/order-store.ts",
        "src/lib/admin/player-store.ts",
        "src/lib/admin/membership-store.ts",
        "src/lib/admin/mantou-store.ts",
        "src/lib/admin/coupon-store.ts",
        "src/lib/admin/guardian-store.ts",
        "src/lib/admin/invoice-store.ts",
        "src/lib/admin/ledger-store.ts",
        "src/lib/admin/redeem-store.ts",
        "src/lib/admin/review-store.ts",
        "src/lib/admin/session-store.ts",
        "src/lib/admin/stats-store.ts",
        "src/lib/admin/support-store.ts",
        "src/lib/admin/audit-store.ts",
        "src/lib/admin/announcement-store.ts",
        "src/lib/chain/chain-admin.ts",
        "src/lib/chain/chain-auto-cancel.ts",
        "src/lib/chain/chain-auto-finalize.ts",
        "src/lib/chain/chain-sponsor.ts",
        "src/lib/chain/chain-event-cursor.ts",
        "src/lib/chain/chain-order-cache.ts",
        "src/lib/chain/chain-order-logger.ts",
        "src/lib/chain/dubhe.ts",
        "src/lib/chain/qy-chain.ts",
        "src/lib/chain/signing-utils.d.ts",
        "src/**/*.d.ts",
        "src/lib/i18n/**",
        "src/lib/atoms/**",
        "src/lib/ledger/**",
        "src/lib/redeem/**",
        "src/lib/services/analytics.ts",
        "src/lib/services/order-store.ts",
        "src/lib/auth/user-auth-client.ts",
        "src/lib/auth/user-session-store.ts",
        "src/lib/shared/client-cache.ts",
        "src/lib/shared/cookie-utils.ts",
        "src/lib/shared/error-utils.ts",
        "src/lib/shared/api-response.ts",
        "src/lib/server-cache.ts",
        "src/lib/http-cache.ts",
        "src/lib/rate-limit.ts",
        "src/lib/risk-policy.ts",
        "src/lib/cron-lock.ts",
        "src/lib/cursor-utils.ts",
        "src/lib/analytics-store.ts",
        "src/lib/utils.ts",
        "src/test/**",
        "src/**/*.test.ts",
        "src/**/*.spec.ts",
      ],
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      "server-only": path.resolve(__dirname, "./src/test/__mocks__/server-only.ts"),
    },
  },
});
