  // Copyright (c) Obelisk Labs, Inc.
  // SPDX-License-Identifier: Apache-2.0
  #[allow(unused_use)]
  
  /* Autogenerated file. Do not edit manually. */
  
  module dubhe::storage_submit {

  use sui::bcs::{to_bytes};

  use std::ascii::{string, String, into_bytes};

  use dubhe::table_id;

  use dubhe::dapp_service::{Self, DappHub};

  use dubhe::dapp_system;

  use dubhe::dapp_key;

  use dubhe::dapp_key::DappKey;

  const TABLE_NAME: vector<u8> = b"storage_submit";

  const TABLE_TYPE: vector<u8> = b"Resource";

  const OFFCHAIN: bool = true;

  public struct StorageSubmit has copy, drop, store {
    dapp_key: String,
    keys: vector<vector<u8>>,
    values: vector<vector<u8>>,
    fee: u256,
  }

  public fun new(dapp_key: String, keys: vector<vector<u8>>, values: vector<vector<u8>>, fee: u256): StorageSubmit {
    StorageSubmit {
            dapp_key,
            keys,
            values,
            fee,
        }
  }

  public fun dapp_key(self: &StorageSubmit): String {
    self.dapp_key
  }

  public fun keys(self: &StorageSubmit): vector<vector<u8>> {
    self.keys
  }

  public fun values(self: &StorageSubmit): vector<vector<u8>> {
    self.values
  }

  public fun fee(self: &StorageSubmit): u256 {
    self.fee
  }

  public fun update_dapp_key(self: &mut StorageSubmit, dapp_key: String) {
    self.dapp_key = dapp_key
  }

  public fun update_keys(self: &mut StorageSubmit, keys: vector<vector<u8>>) {
    self.keys = keys
  }

  public fun update_values(self: &mut StorageSubmit, values: vector<vector<u8>>) {
    self.values = values
  }

  public fun update_fee(self: &mut StorageSubmit, fee: u256) {
    self.fee = fee
  }

  public fun get_table_id(): String {
    string(TABLE_NAME)
  }

  public fun get_key_schemas(): vector<String> {
    vector[]
  }

  public fun get_value_schemas(): vector<String> {
    vector[string(b"String"), string(b"vector<vector<u8>>"), string(b"vector<vector<u8>>"),
    string(b"u256")
    ]
  }

  public fun get_key_names(): vector<String> {
    vector[]
  }

  public fun get_value_names(): vector<String> {
    vector[string(b"dapp_key"), string(b"keys"), string(b"values"),
    string(b"fee")
    ]
  }

  public(package) fun register_table(dapp_hub: &mut DappHub, ctx: &mut TxContext) {
    let dapp_key = dapp_key::new();
    dapp_service::register_table(
            dapp_hub,
             dapp_key,
            string(TABLE_TYPE),
            get_table_id(), 
            get_key_schemas(), 
            get_key_names(), 
            get_value_schemas(), 
            get_value_names(), 
            OFFCHAIN,
            ctx
        );
  }

  public(package) fun set(
    dapp_hub: &mut DappHub,
    dapp_key: String,
    keys: vector<vector<u8>>,
    values: vector<vector<u8>>,
    fee: u256,
  ) {
    let key_tuple = vector::empty();
    let value_tuple = encode(dapp_key, keys, values, fee);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public(package) fun set_struct(dapp_hub: &mut DappHub, storage_submit: StorageSubmit) {
    let key_tuple = vector::empty();
    let value_tuple = encode_struct(storage_submit);
    dapp_service::set_record(dapp_hub, dapp_key::new(), get_table_id(), key_tuple, value_tuple, OFFCHAIN);
  }

  public fun encode(
    dapp_key: String,
    keys: vector<vector<u8>>,
    values: vector<vector<u8>>,
    fee: u256,
  ): vector<vector<u8>> {
    let mut value_tuple = vector::empty();
    value_tuple.push_back(to_bytes(&into_bytes(dapp_key)));
    value_tuple.push_back(to_bytes(&keys));
    value_tuple.push_back(to_bytes(&values));
    value_tuple.push_back(to_bytes(&fee));
    value_tuple
  }

  public fun encode_struct(storage_submit: StorageSubmit): vector<vector<u8>> {
    encode(storage_submit.dapp_key, storage_submit.keys, storage_submit.values, storage_submit.fee)
  }
}
