import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    // Database
    DATABASE_URL: z.string().min(1),
    DATABASE_POOL_URL: z.string().optional(),
    DATABASE_POOLED_URL: z.string().optional(),
    PRISMA_CONNECTION_LIMIT: z.coerce.number().default(5),
    PRISMA_POOL_TIMEOUT: z.coerce.number().default(10),

    // Admin
    ADMIN_DASH_TOKEN: z.string().min(1),
    ADMIN_TOKENS_JSON: z.string().optional(),
    ADMIN_TOKENS: z.string().optional(),
    ADMIN_SESSION_TTL_HOURS: z.coerce.number().default(24),
    ADMIN_RATE_LIMIT_WINDOW_MS: z.coerce.number().default(60000),
    ADMIN_RATE_LIMIT_MAX: z.coerce.number().default(60),
    ADMIN_LOGIN_RATE_LIMIT_MAX: z.coerce.number().default(10),
    ADMIN_IP_ALLOWLIST: z.string().optional(),
    ADMIN_REQUIRE_SESSION: z.enum(["0", "1"]).default("0"),
    ADMIN_AUDIT_LOG_LIMIT: z.coerce.number().default(200),
    ADMIN_PAYMENT_EVENT_LIMIT: z.coerce.number().default(200),
    ADMIN_CHAIN_EVENT_LIMIT: z.coerce.number().default(200),
    LEDGER_ADMIN_TOKEN: z.string().optional(),

    // Auth
    AUTH_MAX_SKEW_MS: z.coerce.number().default(60000),
    AUTH_NONCE_TTL_MS: z.coerce.number().default(300000),
    USER_SESSION_TTL_HOURS: z.coerce.number().default(168),
    AUTH_SESSION_RATE_LIMIT_WINDOW_MS: z.coerce.number().default(60000),
    AUTH_SESSION_RATE_LIMIT_MAX: z.coerce.number().default(20),

    // Chain / Sui
    SUI_RPC_URL: z.string().optional(),
    SUI_NETWORK: z.string().default("mainnet"),
    SUI_ADMIN_PRIVATE_KEY: z.string().optional(),
    SUI_SPONSOR_PRIVATE_KEY: z.string().optional(),
    SUI_SPONSOR_GAS_BUDGET: z.coerce.number().optional(),
    SUI_PACKAGE_ID: z.string().optional(),
    SUI_DAPP_HUB_ID: z.string().optional(),
    SUI_DAPP_HUB_INITIAL_SHARED_VERSION: z.string().optional(),

    // Chain orders
    CHAIN_ORDER_AUTO_CANCEL_HOURS: z.coerce.number().default(24),
    CHAIN_ORDER_AUTO_CANCEL_MAX: z.coerce.number().default(50),
    CHAIN_ORDER_AUTO_COMPLETE_HOURS: z.coerce.number().default(72),
    CHAIN_ORDER_AUTO_COMPLETE_MAX: z.coerce.number().default(50),
    CHAIN_ORDER_AUTO_FINALIZE_MAX: z.coerce.number().default(50),
    CHAIN_ORDER_DEBUG: z.enum(["0", "1"]).default("0"),
    CHAIN_ORDER_CACHE_TTL_MS: z.coerce.number().default(30000),
    CHAIN_ORDER_MAX_CACHE_AGE_MS: z.coerce.number().default(300000),
    CHAIN_MISSING_CLEANUP_ENABLED: z.enum(["0", "1"]).default("0"),
    CHAIN_MISSING_CLEANUP_MAX_AGE_HOURS: z.coerce.number().default(48),
    CHAIN_MISSING_CLEANUP_MAX: z.coerce.number().default(20),

    // Stripe
    STRIPE_SECRET_KEY: z.string().optional(),
    STRIPE_WEBHOOK_SECRET: z.string().optional(),

    // Webhooks
    WECHAT_WEBHOOK_URL: z.string().optional(),

    // Redis
    UPSTASH_REDIS_REST_URL: z.string().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().optional(),

    // Cron
    CRON_SECRET: z.string().optional(),
    CRON_LOCK_TTL_MS: z.coerce.number().default(300000),

    // Rate limits
    ORDER_RATE_LIMIT_WINDOW_MS: z.coerce.number().default(60000),
    ORDER_RATE_LIMIT_MAX: z.coerce.number().default(30),
    PUBLIC_ORDER_RATE_LIMIT_MAX: z.coerce.number().default(120),
    TRACK_RATE_LIMIT_WINDOW_MS: z.coerce.number().default(60000),
    TRACK_RATE_LIMIT_MAX: z.coerce.number().default(120),
    GUARDIAN_RATE_LIMIT_WINDOW_MS: z.coerce.number().default(60000),
    GUARDIAN_RATE_LIMIT_MAX: z.coerce.number().default(10),

    // Maintenance
    ORDER_RETENTION_DAYS: z.coerce.number().default(90),

    // Payment reconciliation
    PAYMENT_RECONCILE_USE_STRIPE: z.enum(["0", "1"]).default("0"),
    PAYMENT_RECONCILE_ALERT_ENABLED: z.enum(["0", "1"]).default("0"),
    PAYMENT_RECONCILE_MISSING_THRESHOLD: z.coerce.number().default(5),
    PAYMENT_RECONCILE_PATCHED_THRESHOLD: z.coerce.number().default(10),
    PAYMENT_RECONCILE_PENDING_THRESHOLD: z.coerce.number().default(10),
    PAYMENT_RECONCILE_ALERT_WEBHOOK_URL: z.string().optional(),

    // Sentry
    SENTRY_DSN: z.string().optional(),
    SENTRY_TRACES_SAMPLE_RATE: z.coerce.number().default(0.1),
    SENTRY_ENVIRONMENT: z.string().optional(),

    // Testing
    E2E_SKIP_WEBHOOK: z.enum(["0", "1"]).default("0"),
  },

  client: {
    NEXT_PUBLIC_SITE_URL: z.string().optional(),
    NEXT_PUBLIC_SUI_RPC_URL: z.string().optional(),
    NEXT_PUBLIC_SUI_NETWORK: z.string().default("mainnet"),
    NEXT_PUBLIC_SUI_PACKAGE_ID: z.string().optional(),
    NEXT_PUBLIC_SUI_DAPP_HUB_ID: z.string().optional(),
    NEXT_PUBLIC_SUI_DAPP_HUB_INITIAL_SHARED_VERSION: z.string().optional(),
    NEXT_PUBLIC_QY_RULESET_ID: z.string().optional(),
    NEXT_PUBLIC_QY_RULESET_ID_L1: z.string().optional(),
    NEXT_PUBLIC_QY_RULESET_ID_L2: z.string().optional(),
    NEXT_PUBLIC_QY_RULESET_ID_L3: z.string().optional(),
    NEXT_PUBLIC_QY_RULESET_ID_L4: z.string().optional(),
    NEXT_PUBLIC_QY_DEFAULT_COMPANION: z.string().optional(),
    NEXT_PUBLIC_ORDER_SOURCE: z.string().optional(),
    NEXT_PUBLIC_CHAIN_ORDERS: z.enum(["0", "1"]).default("0"),
    NEXT_PUBLIC_CHAIN_SPONSOR: z.enum(["0", "1"]).default("0"),
    NEXT_PUBLIC_VISUAL_TEST: z.enum(["0", "1"]).default("0"),
    NEXT_PUBLIC_PASSKEY_AUTOMATION: z.enum(["0", "1"]).default("0"),
    NEXT_PUBLIC_QY_EVENT_LIMIT: z.coerce.number().default(100),
    NEXT_PUBLIC_QY_EVENT_MIN_INTERVAL_MS: z.coerce.number().default(1000),
    NEXT_PUBLIC_PWA_PRECACHE: z.enum(["0", "1"]).default("0"),
    NEXT_PUBLIC_FETCH_MIN_INTERVAL_MS: z.coerce.number().default(10000),
    NEXT_PUBLIC_FETCH_CACHE_TTL_MS: z.coerce.number().default(60000),
    NEXT_PUBLIC_FETCH_THROTTLE_SCOPE: z.string().optional(),
    NEXT_PUBLIC_FETCH_THROTTLE_EXCLUDE: z.string().optional(),
    NEXT_PUBLIC_SENTRY_DSN: z.string().optional(),
    NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE: z.coerce.number().default(0.1),
  },

  runtimeEnv: {
    // Server
    DATABASE_URL: process.env.DATABASE_URL,
    DATABASE_POOL_URL: process.env.DATABASE_POOL_URL,
    DATABASE_POOLED_URL: process.env.DATABASE_POOLED_URL,
    PRISMA_CONNECTION_LIMIT: process.env.PRISMA_CONNECTION_LIMIT,
    PRISMA_POOL_TIMEOUT: process.env.PRISMA_POOL_TIMEOUT,
    ADMIN_DASH_TOKEN: process.env.ADMIN_DASH_TOKEN,
    ADMIN_TOKENS_JSON: process.env.ADMIN_TOKENS_JSON,
    ADMIN_TOKENS: process.env.ADMIN_TOKENS,
    ADMIN_SESSION_TTL_HOURS: process.env.ADMIN_SESSION_TTL_HOURS,
    ADMIN_RATE_LIMIT_WINDOW_MS: process.env.ADMIN_RATE_LIMIT_WINDOW_MS,
    ADMIN_RATE_LIMIT_MAX: process.env.ADMIN_RATE_LIMIT_MAX,
    ADMIN_LOGIN_RATE_LIMIT_MAX: process.env.ADMIN_LOGIN_RATE_LIMIT_MAX,
    ADMIN_IP_ALLOWLIST: process.env.ADMIN_IP_ALLOWLIST,
    ADMIN_REQUIRE_SESSION: process.env.ADMIN_REQUIRE_SESSION,
    ADMIN_AUDIT_LOG_LIMIT: process.env.ADMIN_AUDIT_LOG_LIMIT,
    ADMIN_PAYMENT_EVENT_LIMIT: process.env.ADMIN_PAYMENT_EVENT_LIMIT,
    ADMIN_CHAIN_EVENT_LIMIT: process.env.ADMIN_CHAIN_EVENT_LIMIT,
    LEDGER_ADMIN_TOKEN: process.env.LEDGER_ADMIN_TOKEN,
    AUTH_MAX_SKEW_MS: process.env.AUTH_MAX_SKEW_MS,
    AUTH_NONCE_TTL_MS: process.env.AUTH_NONCE_TTL_MS,
    USER_SESSION_TTL_HOURS: process.env.USER_SESSION_TTL_HOURS,
    AUTH_SESSION_RATE_LIMIT_WINDOW_MS: process.env.AUTH_SESSION_RATE_LIMIT_WINDOW_MS,
    AUTH_SESSION_RATE_LIMIT_MAX: process.env.AUTH_SESSION_RATE_LIMIT_MAX,
    SUI_RPC_URL: process.env.SUI_RPC_URL,
    SUI_NETWORK: process.env.SUI_NETWORK,
    SUI_ADMIN_PRIVATE_KEY: process.env.SUI_ADMIN_PRIVATE_KEY,
    SUI_SPONSOR_PRIVATE_KEY: process.env.SUI_SPONSOR_PRIVATE_KEY,
    SUI_SPONSOR_GAS_BUDGET: process.env.SUI_SPONSOR_GAS_BUDGET,
    SUI_PACKAGE_ID: process.env.SUI_PACKAGE_ID,
    SUI_DAPP_HUB_ID: process.env.SUI_DAPP_HUB_ID,
    SUI_DAPP_HUB_INITIAL_SHARED_VERSION: process.env.SUI_DAPP_HUB_INITIAL_SHARED_VERSION,
    CHAIN_ORDER_AUTO_CANCEL_HOURS: process.env.CHAIN_ORDER_AUTO_CANCEL_HOURS,
    CHAIN_ORDER_AUTO_CANCEL_MAX: process.env.CHAIN_ORDER_AUTO_CANCEL_MAX,
    CHAIN_ORDER_AUTO_COMPLETE_HOURS: process.env.CHAIN_ORDER_AUTO_COMPLETE_HOURS,
    CHAIN_ORDER_AUTO_COMPLETE_MAX: process.env.CHAIN_ORDER_AUTO_COMPLETE_MAX,
    CHAIN_ORDER_AUTO_FINALIZE_MAX: process.env.CHAIN_ORDER_AUTO_FINALIZE_MAX,
    CHAIN_ORDER_DEBUG: process.env.CHAIN_ORDER_DEBUG,
    CHAIN_ORDER_CACHE_TTL_MS: process.env.CHAIN_ORDER_CACHE_TTL_MS,
    CHAIN_ORDER_MAX_CACHE_AGE_MS: process.env.CHAIN_ORDER_MAX_CACHE_AGE_MS,
    CHAIN_MISSING_CLEANUP_ENABLED: process.env.CHAIN_MISSING_CLEANUP_ENABLED,
    CHAIN_MISSING_CLEANUP_MAX_AGE_HOURS: process.env.CHAIN_MISSING_CLEANUP_MAX_AGE_HOURS,
    CHAIN_MISSING_CLEANUP_MAX: process.env.CHAIN_MISSING_CLEANUP_MAX,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    WECHAT_WEBHOOK_URL: process.env.WECHAT_WEBHOOK_URL,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    CRON_SECRET: process.env.CRON_SECRET,
    CRON_LOCK_TTL_MS: process.env.CRON_LOCK_TTL_MS,
    ORDER_RATE_LIMIT_WINDOW_MS: process.env.ORDER_RATE_LIMIT_WINDOW_MS,
    ORDER_RATE_LIMIT_MAX: process.env.ORDER_RATE_LIMIT_MAX,
    PUBLIC_ORDER_RATE_LIMIT_MAX: process.env.PUBLIC_ORDER_RATE_LIMIT_MAX,
    TRACK_RATE_LIMIT_WINDOW_MS: process.env.TRACK_RATE_LIMIT_WINDOW_MS,
    TRACK_RATE_LIMIT_MAX: process.env.TRACK_RATE_LIMIT_MAX,
    GUARDIAN_RATE_LIMIT_WINDOW_MS: process.env.GUARDIAN_RATE_LIMIT_WINDOW_MS,
    GUARDIAN_RATE_LIMIT_MAX: process.env.GUARDIAN_RATE_LIMIT_MAX,
    ORDER_RETENTION_DAYS: process.env.ORDER_RETENTION_DAYS,
    PAYMENT_RECONCILE_USE_STRIPE: process.env.PAYMENT_RECONCILE_USE_STRIPE,
    PAYMENT_RECONCILE_ALERT_ENABLED: process.env.PAYMENT_RECONCILE_ALERT_ENABLED,
    PAYMENT_RECONCILE_MISSING_THRESHOLD: process.env.PAYMENT_RECONCILE_MISSING_THRESHOLD,
    PAYMENT_RECONCILE_PATCHED_THRESHOLD: process.env.PAYMENT_RECONCILE_PATCHED_THRESHOLD,
    PAYMENT_RECONCILE_PENDING_THRESHOLD: process.env.PAYMENT_RECONCILE_PENDING_THRESHOLD,
    PAYMENT_RECONCILE_ALERT_WEBHOOK_URL: process.env.PAYMENT_RECONCILE_ALERT_WEBHOOK_URL,
    SENTRY_DSN: process.env.SENTRY_DSN,
    SENTRY_TRACES_SAMPLE_RATE: process.env.SENTRY_TRACES_SAMPLE_RATE,
    SENTRY_ENVIRONMENT: process.env.SENTRY_ENVIRONMENT,
    E2E_SKIP_WEBHOOK: process.env.E2E_SKIP_WEBHOOK,
    // Client
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_SUI_RPC_URL: process.env.NEXT_PUBLIC_SUI_RPC_URL,
    NEXT_PUBLIC_SUI_NETWORK: process.env.NEXT_PUBLIC_SUI_NETWORK,
    NEXT_PUBLIC_SUI_PACKAGE_ID: process.env.NEXT_PUBLIC_SUI_PACKAGE_ID,
    NEXT_PUBLIC_SUI_DAPP_HUB_ID: process.env.NEXT_PUBLIC_SUI_DAPP_HUB_ID,
    NEXT_PUBLIC_SUI_DAPP_HUB_INITIAL_SHARED_VERSION:
      process.env.NEXT_PUBLIC_SUI_DAPP_HUB_INITIAL_SHARED_VERSION,
    NEXT_PUBLIC_QY_RULESET_ID: process.env.NEXT_PUBLIC_QY_RULESET_ID,
    NEXT_PUBLIC_QY_RULESET_ID_L1: process.env.NEXT_PUBLIC_QY_RULESET_ID_L1,
    NEXT_PUBLIC_QY_RULESET_ID_L2: process.env.NEXT_PUBLIC_QY_RULESET_ID_L2,
    NEXT_PUBLIC_QY_RULESET_ID_L3: process.env.NEXT_PUBLIC_QY_RULESET_ID_L3,
    NEXT_PUBLIC_QY_RULESET_ID_L4: process.env.NEXT_PUBLIC_QY_RULESET_ID_L4,
    NEXT_PUBLIC_QY_DEFAULT_COMPANION: process.env.NEXT_PUBLIC_QY_DEFAULT_COMPANION,
    NEXT_PUBLIC_ORDER_SOURCE: process.env.NEXT_PUBLIC_ORDER_SOURCE,
    NEXT_PUBLIC_CHAIN_ORDERS: process.env.NEXT_PUBLIC_CHAIN_ORDERS,
    NEXT_PUBLIC_CHAIN_SPONSOR: process.env.NEXT_PUBLIC_CHAIN_SPONSOR,
    NEXT_PUBLIC_VISUAL_TEST: process.env.NEXT_PUBLIC_VISUAL_TEST,
    NEXT_PUBLIC_PASSKEY_AUTOMATION: process.env.NEXT_PUBLIC_PASSKEY_AUTOMATION,
    NEXT_PUBLIC_QY_EVENT_LIMIT: process.env.NEXT_PUBLIC_QY_EVENT_LIMIT,
    NEXT_PUBLIC_QY_EVENT_MIN_INTERVAL_MS: process.env.NEXT_PUBLIC_QY_EVENT_MIN_INTERVAL_MS,
    NEXT_PUBLIC_PWA_PRECACHE: process.env.NEXT_PUBLIC_PWA_PRECACHE,
    NEXT_PUBLIC_FETCH_MIN_INTERVAL_MS: process.env.NEXT_PUBLIC_FETCH_MIN_INTERVAL_MS,
    NEXT_PUBLIC_FETCH_CACHE_TTL_MS: process.env.NEXT_PUBLIC_FETCH_CACHE_TTL_MS,
    NEXT_PUBLIC_FETCH_THROTTLE_SCOPE: process.env.NEXT_PUBLIC_FETCH_THROTTLE_SCOPE,
    NEXT_PUBLIC_FETCH_THROTTLE_EXCLUDE: process.env.NEXT_PUBLIC_FETCH_THROTTLE_EXCLUDE,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE: process.env.NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE,
  },

  skipValidation: process.env.SKIP_ENV_VALIDATION === "1",
});
